# -*- coding: utf-8 -*-
"""cigarette

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IbvENg7-8DLE5MCHsm6Rh2SdAn2CPpYl
"""

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

!rm -rf /content/drive

from google.colab import drive

drive.mount('/content/drive')

import os

print(os.listdir("/content/drive/MyDrive"))

print(os.listdir("/content/drive/MyDrive/cigarette"))

import os

path = "/content/drive/MyDrive/cigarette/dataset"

for root, dirs, files in os.walk(path):
    level = root.replace(path, "").count(os.sep)
    indent = "  " * level
    print(indent + os.path.basename(root) + "/")

    for file in files:
        print(indent + "  " + file)

"""แตก ZIP"""

import zipfile
import os

zip_path = "/content/drive/MyDrive/cigarette/dataset/smoking.v2-2024-06-10-2-50pm.yolo26.zip"

extract_path = "/content/drive/MyDrive/cigarette/dataset/smoking"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ แตกไฟล์เรียบร้อย")

"""เช็กไฟล์ข้างใน"""

import os

for root, dirs, files in os.walk(
    "/content/drive/MyDrive/cigarette/dataset/smoking"
):
    level = root.replace(
        "/content/drive/MyDrive/cigarette/dataset/smoking", ""
    ).count(os.sep)

    indent = "  " * level
    print(indent + os.path.basename(root) + "/")

    for file in files:
        print(indent + "  " + file)

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model.train(
    data="/content/drive/MyDrive/cigarette/dataset/smoking/data.yaml",
    epochs=100,
    imgsz=640,
    batch=16,
    name="cigarette_detection"
)

import os

for root, dirs, files in os.walk("/content"):
    if "best.pt" in files:
        print(os.path.join(root, "best.pt"))

import shutil
import os
import glob

# Define the expected base directory for YOLO runs
yolo_runs_dir = "/content/runs/detect/"
model_name_prefix = "cigarette_detection" # From the name='cigarette_detection' argument

actual_source_path = None

# Search for the 'best.pt' file in directories starting with 'cigarette_detection'
# This accounts for cases like 'cigarette_detection', 'cigarette_detection2', etc.
search_pattern = os.path.join(yolo_runs_dir, f"{model_name_prefix}*/weights/best.pt")
found_files = glob.glob(search_pattern)

if found_files:
    # If multiple files are found, take the most recently modified one
    actual_source_path = max(found_files, key=os.path.getmtime)
else:
    # Fallback: if no specific 'cigarette_detection' runs found, try a broader search
    # This might catch if the model_name_prefix was slightly wrong or other runs exist
    search_pattern_broad = os.path.join(yolo_runs_dir, "*/weights/best.pt")
    found_files_broad = glob.glob(search_pattern_broad)
    if found_files_broad:
        actual_source_path = max(found_files_broad, key=os.path.getmtime)


if actual_source_path:
    source = actual_source_path
    destination = "/content/drive/MyDrive/cigarette/best.pt"

    os.makedirs(os.path.dirname(destination), exist_ok=True) # Ensure destination directory exists

    shutil.copy2(source, destination)

    print("✅ บันทึก best.pt ลง Google Drive แล้ว")
    print(f"Model copied from: {source}")
    print(f"Model saved to: {destination}")
else:
    print("❌ Error: 'best.pt' model file not found after training.")
    print(f"Please check the output directory for your YOLO training results in {yolo_runs_dir}")
    print(f"Expected file pattern: {search_pattern}")

import os

print("ค้นหาไฟล์ .pt ใน /content ...")

found = []

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.endswith(".pt"):
            path = os.path.join(root, file)
            found.append(path)
            print("พบ:", path)

if not found:
    print("❌ ไม่พบไฟล์ .pt ใน /content")

import os

print("🔍 กำลังค้นหาโมเดล .pt ใน Google Drive...\n")

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for file in files:
        if file.endswith(".pt"):
            print(os.path.join(root, file))

import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for file in files:
        if "cigarette" in file.lower() or "cigarette" in root.lower():
            print(os.path.join(root, file))