# -*- coding: utf-8 -*-
"""kids_acsident.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RA4aRfPEcXjeoKdgBFgwVT0ZSEu3qOYB
"""

import os
from google.colab import drive
drive.mount('/content/drive')

# คัดลอกโฟลเดอร์ train, valid และ data.yaml จาก Drive มาไว้ที่ Colab
!cp -r /content/drive/MyDrive/Child_Pose_Project/train /content/
!cp -r /content/drive/MyDrive/Child_Pose_Project/valid /content/
!cp /content/drive/MyDrive/Child_Pose_Project/data.yaml /content/

print("ดึงไฟล์ทั้งหมดมาไว้บนเครื่อง Colab เรียบร้อย!")

# แก้ไข path ใน data.yaml ให้อ่านจากเครื่อง Colab Direct
with open('/content/data.yaml', 'r') as f:
    content = f.read()

with open('/content/data.yaml', 'w') as f:
    f.write("path: /content\n")
    f.write("train: train/images\n")
    f.write("val: valid/images\n\n")
    lines = content.splitlines()
    for line in lines:
        if not any(line.startswith(k) for k in ['path:', 'train:', 'val:', 'test:']):
            f.write(line + '\n')

print("ปรับปรุง data.yaml เรียบร้อย!")

import cv2
import glob
import matplotlib.pyplot as plt
from ultralytics import YOLO

# 1. โหลด Weight best.pt ล่าสุดที่เทรนเก็บไว้ใน Drive
MODEL_PATH = '/content/drive/MyDrive/Child_Pose_Project/runs/child_climbing_pose/weights/best.pt'
trained_model = YOLO(MODEL_PATH)

# 2. Logic วิเคราะห์ Pose เด็กเสี่ยงตก ( Clibming Alert )
def analyze_climbing_risk(kpts):
    if len(kpts) < 17:
        return "NORMAL", (0, 255, 0)

    # อ่านพิกัด Y (ยิ่งน้อยยิ่งสูง)
    nose_y = kpts[0][1] if kpts[0][2] > 0.3 else None
    wrist_l_y, wrist_r_y = kpts[9][1], kpts[10][1]
    hip_l_y, hip_r_y = kpts[11][1], kpts[12][1]
    ankle_l_y, ankle_r_y = kpts[15][1], kpts[16][1]

    avg_hip_y = (hip_l_y + hip_r_y) / 2.0

    # มืออยู่สูงกว่าหัว
    hands_up = False
    if nose_y:
        hands_up = (wrist_l_y < nose_y and kpts[9][2] > 0.3) or (wrist_r_y < nose_y and kpts[10][2] > 0.3)

    # เท้าถูกยกสูงระดับสะโพก
    feet_climbing = (ankle_l_y < avg_hip_y and kpts[15][2] > 0.3) or (ankle_r_y < avg_hip_y and kpts[16][2] > 0.3)

    if hands_up and feet_climbing:
        return "DANGER: CLIMBING DETECTED!", (0, 0, 255) # แดง
    elif hands_up or feet_climbing:
        return "WARNING: HIGH RISK POSE", (0, 165, 255) # ส้ม
    else:
        return "SAFE", (0, 255, 0) # เขียว

# 3. สุ่มรูปมาแสดงผลหน้าจอตรวจจับ
test_images = glob.glob('/content/valid/images/*.jpg')

if test_images:
    for img_path in test_images[:3]:
        frame = cv2.imread(img_path)
        results = trained_model(img_path, conf=0.25)

        for r in results:
            frame = r.plot() # วาด Skeleton

            if r.keypoints is not None and len(r.keypoints.data) > 0:
                for idx, kpt_data in enumerate(r.keypoints.data.cpu().numpy()):
                    status, color = analyze_climbing_risk(kpt_data)

                    # แสดง Banner เตือนแบบในภาพตัวอย่าง
                    cv2.rectangle(frame, (10, 10 + (idx * 50)), (550, 55 + (idx * 50)), (0, 0, 0), -1)
                    cv2.putText(frame, f"Child #{idx+1}: {status}",
                                (20, 42 + (idx * 50)), cv2.FONT_HERSHEY_SIMPLEX,
                                0.8, color, 2, cv2.LINE_AA)

        img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        plt.figure(figsize=(10, 6))
        plt.imshow(img_rgb)
        plt.axis('off')
        plt.show()
else:
    print("ไม่พบรูปใน /content/valid/images/ ลองอัปโหลดรูปเด็กมาทดสอบใน /content/ ได้ครับ")

import cv2
from ultralytics import YOLO

# 1. โหลดโมเดลที่ดาวน์โหลดมาไว้ในเครื่อง (ใส่ path ของไฟล์ best.pt)
model = YOLO('/content/drive/MyDrive/Child_Pose_Project/runs/child_climbing_pose/weights/best.pt')

# 2. ฟังก์ชันวิเคราะห์ท่าทางเสี่ยงตก
def analyze_climbing_risk(kpts):
    if len(kpts) < 17:
        return "NORMAL", (0, 255, 0)

    nose_y = kpts[0][1] if kpts[0][2] > 0.3 else None
    wrist_l_y, wrist_r_y = kpts[9][1], kpts[10][1]
    hip_l_y, hip_r_y = kpts[11][1], kpts[12][1]
    ankle_l_y, ankle_r_y = kpts[15][1], kpts[16][1]

    avg_hip_y = (hip_l_y + hip_r_y) / 2.0

    hands_up = False
    if nose_y:
        hands_up = (wrist_l_y < nose_y and kpts[9][2] > 0.3) or (wrist_r_y < nose_y and kpts[10][2] > 0.3)

    feet_climbing = (ankle_l_y < avg_hip_y and kpts[15][2] > 0.3) or (ankle_r_y < avg_hip_y and kpts[16][2] > 0.3)

    if hands_up and feet_climbing:
        return "DANGER: CLIMBING DETECTED!", (0, 0, 255)
    elif hands_up or feet_climbing:
        return "WARNING: HIGH RISK POSE", (0, 165, 255)
    else:
        return "SAFE", (0, 255, 0)

# 3. เปิดกล้อง Webcam (0 = กล้องหลักของคอม)
cap = cv2.VideoCapture(0)

while cap.isOpened():
    success, frame = cap.read()
    if not success:
        break

    # ประมวลผลเฟรมภาพ
    results = model(frame, conf=0.3, verbose=False)

    for r in results:
        frame = r.plot()
        if r.keypoints is not None and len(r.keypoints.data) > 0:
            for idx, kpt_data in enumerate(r.keypoints.data.cpu().numpy()):
                status, color = analyze_climbing_risk(kpt_data)

                # แสดง Banner แจ้งเตือนสไตล์ UI โปรเจกต์
                cv2.rectangle(frame, (10, 10 + (idx * 45)), (500, 50 + (idx * 45)), (0, 0, 0), -1)
                cv2.putText(frame, f"Child #{idx+1}: {status}",
                            (15, 38 + (idx * 45)), cv2.FONT_HERSHEY_SIMPLEX,
                            0.7, color, 2, cv2.LINE_AA)

    # เปิดหน้าต่างแสดงภาพ Real-time
    cv2.imshow("NurseryGuard AI - Climbing Detection", frame)

    # กดปุ่ม 'q' เพื่อออกจากโปรแกรม
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

import cv2
import numpy as np
import base64
import time
import requests
import json
from ultralytics import YOLO
from google.colab.output import eval_js
from IPython.display import display, Javascript, HTML

# ---------------------------------------------------------
# 1. รับค่า LINE Official Notification (Messaging API) ผ่าน input box
# ---------------------------------------------------------
LINE_ACCESS_TOKEN = input("LINE Channel Access Token: ")
LINE_USER_ID = input("LINE User ID: ")

# ฟังก์ชันส่งข้อความแจ้งเตือนเข้า LINE Official
def send_line_message_text(message):
    url = 'https://api.line.me/v2/bot/message/push'
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {LINE_ACCESS_TOKEN}'
    }
    data = {
        'to': LINE_USER_ID,
        'messages': [{'type': 'text', 'text': message}]
    }

    try:
        response = requests.post(url, headers=headers, data=json.dumps(data), timeout=5)
        if response.status_code == 200:
            print("[LINE] ส่งข้อความแจ้งเตือนเรียบร้อย!")
        else:
            print(f"[LINE] ส่งข้อความล้มเหลว รหัสสถานะ: {response.status_code}")
    except Exception as e:
        print(f"[LINE] เกิดข้อผิดพลาดในการส่งข้อความ: {e}")

# Note: เนื่องจากข้อจำกัดของ Colab ที่ทำงานบน Cloud การส่ง "รูปภาพ" จากกล้องสดเข้าไปที่ LINE Official โดยตรง (Messaging API) จะทำได้ยากและซับซ้อนมาก
# โค้ดนี้จะเน้นส่ง "ข้อความแจ้งเตือน" เป็นหลักเมื่อตรวจเจอเหตุการณ์ เพื่อให้รันได้ง่ายที่สุดครับ

# ---------------------------------------------------------
# 2. โหลด Model ตรวจจับท่าทาง และกำหนด logic ปีนป่าย
# ---------------------------------------------------------
MODEL_PATH = '/content/drive/MyDrive/Child_Pose_Project/runs/child_climbing_pose/weights/best.pt'
try:
    model = YOLO(MODEL_PATH)
except:
    # หากยังไม่มี model ของตัวเอง สามารถใช้ตัวเริ่มต้นก่อนได้ครับ
    print("[MODEL] ไม่พบไฟล์ Model ของคุณ, ใช้ yolo11n-pose ชั่วคราว")
    model = YOLO('yolo11n-pose.pt')

last_alert_time = 0
ALERT_COOLDOWN = 10  # ป้องกันแจ้งเตือนรัวๆ (ส่งทุกๆ 10 วินาทีเมื่อเจอเหตุการณ์เดิม)

def analyze_and_detect(frame):
    global last_alert_time
    results = model(frame, conf=0.35, verbose=False) # ใช้ confidence 0.35 ขึ้นไป

    is_danger = False
    alert_msg = ""

    for r in results:
        # วาดกล่องตรวจจับและเส้นท่าทาง
        frame = r.plot()

        if r.keypoints is not None and len(r.keypoints.data) > 0:
            for idx, kpt_data in enumerate(r.keypoints.data.cpu().numpy()):
                kpts = kpt_data
                if len(kpts) < 17: continue

                # Logic วิเคราะห์การปีนป่ายสิ่งของ (โต๊ะ, เก้าอี้, ที่สูง)
                # ใช้พิกัด Y (ค่าน้อย = อยู่ตำแหน่งสูงในภาพ) ของส่วนต่างๆ
                nose_y = kpts[0][1] if kpts[0][2] > 0.3 else None
                wrist_l_y, wrist_r_y = kpts[9][1], kpts[10][1]
                hip_l_y, hip_r_y = kpts[11][1], kpts[12][1]
                ankle_l_y, ankle_r_y = kpts[15][1], kpts[16][1]

                avg_hip_y = (hip_l_y + hip_r_y) / 2.0

                # เงื่อนไข 1: ข้อมืออยู่สูงกว่าหัว (พยายามเกาะ/เหนี่ยว)
                hands_up = False
                if nose_y:
                    hands_up = (wrist_l_y < nose_y and kpts[9][2] > 0.3) or (wrist_r_y < nose_y and kpts[10][2] > 0.3)

                # เงื่อนไข 2: เท้ายกสูงขึ้นระดับสะโพก (พยายามก้าวปีน)
                feet_climbing = (ankle_l_y < avg_hip_y and kpts[15][2] > 0.3) or (ankle_r_y < avg_hip_y and kpts[16][2] > 0.3)

                # สรุปผล
                if hands_up and feet_climbing:
                    status = "DANGER: CLIMBING DETECTED!"
                    color = (0, 0, 255) # สีแดง
                    is_danger = True
                    # ข้อความแจ้งเตือนภัยแบบต่างๆ ทั้งหน้าและหลัง
                    alert_msg = f"⚠️ [แจ้งเตือนภัยด่วน!] ตรวจพบเด็กคนที่ #{idx+1} มีพฤติกรรมผิดปกติ กำลังปีนป่ายสิ่งของเสี่ยงตก!"
                elif hands_up or feet_climbing:
                    status = "WARNING: HIGH RISK POSE"
                    color = (0, 165, 255) # สีส้ม
                else:
                    status = "SAFE"
                    color = (0, 255, 0) # สีเขียว

                # วาดสถานะบนหน้าจอวิดีโอ
                cv2.rectangle(frame, (10, 10 + (idx * 45)), (550, 50 + (idx * 45)), (0, 0, 0), -1)
                cv2.putText(frame, f"Child #{idx+1}: {status}", (15, 38 + (idx * 45)), cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2, cv2.LINE_AA)

    # ส่ง LINE เมื่อเจอเคสอันตราย และพ้นระยะ Cooldown
    current_time = time.time()
    if is_danger and (current_time - last_alert_time > ALERT_COOLDOWN):
        send_line_message_text(alert_msg)
        last_alert_time = current_time

    return frame

# ---------------------------------------------------------
# 3. โค้ด JavaScript เพื่อเปิดกล้องเว็บแคมเรียลไทม์
# ---------------------------------------------------------
def setup_webcam():
    js = Javascript('''
    async function setupWebcam() {
      // ลบ UI เก่าออกก่อน
      const oldDiv = document.getElementById('webcam-container');
      if (oldDiv) oldDiv.remove();

      const div = document.createElement('div');
      div.id = 'webcam-container';
      div.innerHTML = '<h3 style="color:#0080ff;">NurseryGuard AI - Real-time Detection & Line Offical Alert</h3>';

      const video = document.createElement('video');
      video.id = 'webcam';
      video.style.display = 'none'; // ซ่อนวิดีโอต้นฉบับ
      video.width = 640;
      video.height = 480;

      const stream = await navigator.mediaDevices.getUserMedia({ video: { width: 640, height: 480 } });
      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      const canvas = document.createElement('canvas');
      canvas.width = 640;
      canvas.height = 480;

      const img = document.createElement('img');
      img.id = 'output-frame';
      img.style.border = '4px solid #0080ff';
      img.style.borderRadius = '8px';
      div.appendChild(img);

      window.webcamStream = { video, canvas, ctx: canvas.getContext('2d'), img };
    }
    setupWebcam();
    ''')
    display(js)

def get_frame():
    js = Javascript('''
    (async () => {
      if (!window.webcamStream) return null;
      const { video, canvas, ctx } = window.webcamStream;
      ctx.drawImage(video, 0, 0, 640, 480);
      return canvas.toDataURL('image/jpeg', 0.6); // ย่อคุณภาพเหลือ 0.6 เพื่อความเร็ว
    })()
    ''')
    data_url = eval_js(js)
    if not data_url: return None
    header, encoded = data_url.split(",", 1)
    data = base64.b64decode(encoded)
    np_arr = np.frombuffer(data, np.uint8)
    return cv2.imdecode(np_arr, cv2.IMREAD_COLOR)

# ---------------------------------------------------------
# 4. เริ่มรันกล้องตรวจจับสด
# ---------------------------------------------------------
setup_webcam()
time.sleep(2) # รอระบบเปิดกล้อง

print("กำลังเปิดกล้อง... (หากไม่ขึ้นภาพ ให้ตรวจสอบสิทธิ์การใช้กล้องที่ Browser ของคุณนะครับ)")

while True:
    try:
        frame = get_frame()
        if frame is None: continue

        # ตรวจจับภัยและประมวลผล
        processed_frame = analyze_and_detect(frame)

        # แปลงภาพกลับมาแสดงผลบน Colab (เรียลไทม์)
        _, buffer = cv2.imencode('.jpg', processed_frame)
        img_b64 = base64.b64encode(buffer).decode('utf-8')

        display(Javascript(f'''
        if (window.webcamStream && window.webcamStream.img) {{
            window.webcamStream.img.src = 'data:image/jpeg;base64,{img_b64}';
        }}
        '''))

    except Exception as e:
        print(f"[SYSTEM] หยุดการทำงาน: {e}")
        break

def analyze_and_detect(frame):
    global last_alert_time

    # เพิ่ม conf และ iou (NMS) เพื่อตัดกล่องซ้อนมั่ว
    results = model(frame, conf=0.30, iou=0.45, verbose=False)

    is_danger = False
    alert_msg = ""

    h_img, w_img, _ = frame.shape

    for r in results:
        # วาดกล่อง Pose / Bounding Box พื้นฐาน
        frame = r.plot()

        # ---------------------------------------------------------------------
        # 1. ตรวจจับโดยใช้ Bounding Box (ทำงานชัวร์ 100% แม้ Keypoints จะหลุด)
        # ---------------------------------------------------------------------
        if r.boxes is not None and len(r.boxes) > 0:
            boxes = r.boxes.xyxy.cpu().numpy() # [x1, y1, x2, y2]
            clfs = r.boxes.conf.cpu().numpy()

            for idx, (box, conf) in enumerate(zip(boxes, clfs)):
                x1, y1, x2, y2 = box
                box_h = y2 - y1
                box_w = x2 - x1

                # เช็กตำแหน่งส่วนบนสุดของกล่อง (y1) และตำแหน่งกึ่งกลางแนวตั้ง
                center_y = (y1 + y2) / 2.0

                # เงื่อนไขการปีนป่าย:
                # 1. ตัวเด็กอยู่โซนกลาง-บนของภาพ (y1 อยู่ครึ่งบนของจอ)
                # 2. หรือกล่องมีความสูงยืดขนานกับโต๊ะ
                is_climbing_box = (y1 < h_img * 0.6)

                # ---------------------------------------------------------------------
                # 2. ตรวจจับร่วมกับ Keypoints (ถ้ามี)
                # ---------------------------------------------------------------------
                is_climbing_kpt = False
                if r.keypoints is not None and len(r.keypoints.data) > idx:
                    kpts = r.keypoints.data[idx].cpu().numpy()
                    if len(kpts) >= 17:
                        # ดึงค่าจุดที่มี confidence เกิน 0.1
                        valid_y = [kpt[1] for kpt in kpts if kpt[2] > 0.1]
                        if len(valid_y) > 0:
                            min_y = min(valid_y)
                            if min_y < h_img * 0.65:
                                is_climbing_kpt = True

                # ---------------------------------------------------------------------
                # สรุปผลสถานะการแจ้งเตือน
                # ---------------------------------------------------------------------
                if is_climbing_box or is_climbing_kpt:
                    status = "DANGER: CLIMBING DETECTED!"
                    color = (0, 0, 255) # สีแดงสด (BGR)
                    is_danger = True
                    alert_msg = f"⚠️ [แจ้งเตือนภัยด่วน!] ตรวจพบเด็กคนที่ #{idx+1} มีพฤติกรรมเสี่ยงปีนป่ายโต๊ะ/เก้าอี้!"
                else:
                    status = "NORMAL"
                    color = (0, 255, 0) # สีเขียว

                # ---------------------------------------------------------------------
                # 3. วาดแถบข้อความเตือนภัยสีแดงบนภาพ (ให้เห็นชัดเจนแน่นอน)
                # ---------------------------------------------------------------------
                # สร้างแถบพื้นหลังสีดำขอบสีแดง/เขียว ด้านบนภาพ
                top_offset = 20 + (idx * 55)
                cv2.rectangle(frame, (15, top_offset), (615, top_offset + 45), (0, 0, 0), -1)
                cv2.rectangle(frame, (15, top_offset), (615, top_offset + 45), color, 3)
                cv2.putText(frame, f"Child #{idx+1}: {status}",
                            (25, top_offset + 32), cv2.FONT_HERSHEY_SIMPLEX,
                            0.75, color, 2, cv2.LINE_AA)

    # -------------------------------------------------------------------------
    # 4. แสดงแถบคาดเตือนภัยสีแดงด้านล่างจอ + ส่ง LINE Alert
    # -------------------------------------------------------------------------
    if is_danger:
        # แถบแดงคาดล่างจอ
        cv2.rectangle(frame, (0, h_img - 50), (w_img, h_img), (0, 0, 255), -1)
        cv2.putText(frame, "⚠️ WARNING: CHILD CLIMBING / RISK DETECTED!",
                    (25, h_img - 15), cv2.FONT_HERSHEY_SIMPLEX,
                    0.7, (255, 255, 255), 2, cv2.LINE_AA)

        # ส่งข้อความเข้า LINE (เว้นระยะ cooldown 10 วินาที)
        current_time = time.time()
        if current_time - last_alert_time > ALERT_COOLDOWN:
            send_line_message_text(alert_msg)
            last_alert_time = current_time

    return frame

import cv2
import numpy as np
import base64
import time
import requests
import json
import datetime
from IPython.display import display, Javascript, clear_output
from google.colab.output import eval_js
from ultralytics import YOLO

# ---------------------------------------------------------
# 1. ตั้งค่า LINE Official Account (Messaging API)
# ---------------------------------------------------------
# 🔑 วาง Token และ User ID ที่ได้จาก LINE Developers Console ของคุณเองที่นี่
LINE_ACCESS_TOKEN = 'วาง_CHANNEL_ACCESS_TOKEN_ที่นี่'  # ห้ามใส่ค่าจริงแล้ว commit
LINE_USER_ID = 'วาง_USER_ID_ที่นี่'

def send_line_official_custom(status_text, confidence=0.0):
    if 'วาง_' in LINE_ACCESS_TOKEN or not LINE_ACCESS_TOKEN:
        print("[LINE Alert] ⚠️ ยังไม่ได้ใส่ LINE_ACCESS_TOKEN ใหม่ของคุณ")
        return

    url = 'https://api.line.me/v2/bot/message/push'
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {LINE_ACCESS_TOKEN.strip()}'
    }

    current_time = datetime.datetime.now().strftime("%d/%m/%Y %H:%M:%S")

    msg_text = f"""🚨 NurseryGuard ALERT 🚨

⚠️ ตรวจพบพฤติกรรมเสี่ยงปีนป่าย

👶 Status: {status_text}
📊 Confidence: {confidence:.2f}
⏰ เวลา: {current_time}

📸 บันทึกภาพหลักฐานแล้ว"""

    payload = {
        'to': LINE_USER_ID.strip(),
        'messages': [{'type': 'text', 'text': msg_text}]
    }

    try:
        response = requests.post(url, headers=headers, data=json.dumps(payload), timeout=5)
        if response.status_code == 200:
            print("[LINE Alert] ✅ ส่งแจ้งเตือนสำเร็จ! (Code 200)")
        else:
            print(f"[LINE Alert] ❌ ส่งล้มเหลว Code: {response.status_code} | {response.text}")
    except Exception as e:
        print(f"[LINE Alert] ❌ เกิดข้อผิดพลาด: {e}")

# ---------------------------------------------------------
# 2. โหลด Weight และระบบวิเคราะห์ Pose ปีนป่าย
# ---------------------------------------------------------
MODEL_PATH = '/content/drive/MyDrive/Child_Pose_Project/runs/child_climbing_pose/weights/best.pt'
try:
    model = YOLO(MODEL_PATH)
    print(f"[MODEL] โหลด Model สำเร็จ: {MODEL_PATH}")
except Exception as e:
    print(f"[MODEL] ใช้ yolo11n-pose ชั่วคราว (Error: {e})")
    model = YOLO('yolo11n-pose.pt')

last_alert_time = 0
ALERT_COOLDOWN = 10  # ส่งเตือนห่างกันอย่างน้อย 10 วินาที

def analyze_and_detect(frame):
    global last_alert_time
    h_img, w_img, _ = frame.shape

    results = model(frame, conf=0.25, verbose=False)

    is_danger = False
    max_conf = 0.0
    detected_children = []

    for r in results:
        frame = r.plot()

        if r.keypoints is not None and len(r.keypoints.data) > 0:
            for idx, kpt_data in enumerate(r.keypoints.data.cpu().numpy()):
                kpts = kpt_data
                valid_y_pts = [kpts[i][1] for i in range(len(kpts)) if kpts[i][2] > 0.10]

                if len(valid_y_pts) > 0:
                    min_y = min(valid_y_pts)
                    avg_y = np.mean(valid_y_pts)

                    if r.boxes is not None and len(r.boxes) > idx:
                        max_conf = float(r.boxes.conf[idx].cpu().numpy())
                    else:
                        max_conf = 0.85

                    if min_y < (h_img * 0.68) or avg_y < (h_img * 0.70):
                        status = "DANGER: CLIMBING DETECTED!"
                        color = (0, 0, 255)
                        is_danger = True
                    else:
                        status = "NORMAL"
                        color = (0, 255, 0)

                    detected_children.append((status, color))

        elif r.boxes is not None and len(r.boxes) > 0:
            boxes = r.boxes.xyxy.cpu().numpy()
            confs = r.boxes.conf.cpu().numpy()
            for box, conf in zip(boxes, confs):
                x1, y1, x2, y2 = box
                if y1 < (h_img * 0.60):
                    status = "DANGER: CLIMBING DETECTED!"
                    color = (0, 0, 255)
                    is_danger = True
                    max_conf = float(conf)
                    detected_children.append((status, color))
                    break

    # ---------------------------------------------------------
    # 3. วาดป้ายเตือนบนหน้าจอ
    # ---------------------------------------------------------
    if len(detected_children) > 0:
        for idx, (status, color) in enumerate(detected_children):
            top_y = 15 + (idx * 45)
            cv2.rectangle(frame, (10, top_y), (580, top_y + 40), (0, 0, 0), -1)
            cv2.rectangle(frame, (10, top_y), (580, top_y + 40), color, 3)
            cv2.putText(frame, f"Child #{idx+1}: {status}",
                        (20, top_y + 28), cv2.FONT_HERSHEY_SIMPLEX,
                        0.7, color, 2, cv2.LINE_AA)

    if is_danger:
        cv2.rectangle(frame, (0, h_img - 45), (w_img, h_img), (0, 0, 255), -1)
        cv2.putText(frame, "WARNING: CHILD CLIMBING DETECTED!",
                    (20, h_img - 15), cv2.FONT_HERSHEY_SIMPLEX,
                    0.7, (255, 255, 255), 2, cv2.LINE_AA)

        current_time = time.time()
        if current_time - last_alert_time > ALERT_COOLDOWN:
            send_line_official_custom("Child Climbing Detected!", confidence=max_conf)
            last_alert_time = current_time

    return frame

# ---------------------------------------------------------
# 4. JavaScript เปิดกล้อง Colab
# ---------------------------------------------------------
webcam_setup_js = """
async function setupWebcam() {
  if (window.webcamStream && window.webcamStream.video && window.webcamStream.video.srcObject) {
    window.webcamStream.video.srcObject.getTracks().forEach(track => track.stop());
  }
  const oldDiv = document.getElementById('webcam-container');
  if (oldDiv) oldDiv.remove();

  const div = document.createElement('div');
  div.id = 'webcam-container';
  div.innerHTML = '<h3 style="color:#0080ff; font-family: sans-serif;">NurseryGuard AI - Real-time Detection Stream</h3>';

  const video = document.createElement('video');
  video.id = 'webcam';
  video.style.display = 'none';
  video.width = 640;
  video.height = 480;

  const stream = await navigator.mediaDevices.getUserMedia({ video: { width: 640, height: 480 } });
  document.body.appendChild(div);
  div.appendChild(video);
  video.srcObject = stream;
  await video.play();

  const canvas = document.createElement('canvas');
  canvas.width = 640;
  canvas.height = 480;

  const outputCanvas = document.createElement('canvas');
  outputCanvas.id = 'output-canvas';
  outputCanvas.width = 640;
  outputCanvas.height = 480;
  outputCanvas.style.border = '4px solid #0080ff';
  outputCanvas.style.borderRadius = '8px';
  div.appendChild(outputCanvas);

  window.webcamStream = { video, canvas, ctx: canvas.getContext('2d'), outputCanvas, outputCtx: outputCanvas.getContext('2d') };
}
"""

webcam_get_frame_js = """
(async () => {
  if (!window.webcamStream) return null;
  const { video, canvas, ctx } = window.webcamStream;
  ctx.drawImage(video, 0, 0, 640, 480);
  return canvas.toDataURL('image/jpeg', 0.6);
})()
"""

webcam_show_frame_template = """
(async () => {{
  if (window.webcamStream && window.webcamStream.outputCanvas) {{
    const ctx = window.webcamStream.outputCtx;
    const img = new Image();
    img.onload = () => ctx.drawImage(img, 0, 0, 640, 480);
    img.src = "{data_url}";
  }}
}})()
"""

# ---------------------------------------------------------
# 5. เริ่มรันกล้อง
# ---------------------------------------------------------
clear_output()
eval_js(webcam_setup_js)
eval_js("setupWebcam()")

time.sleep(2)
print("กำลังเปิดกล้องสด...")

while True:
    try:
        data_url = eval_js(webcam_get_frame_js)
        if data_url is None:
            continue

        header, encoded = data_url.split(",", 1)
        data = base64.b64decode(encoded)
        np_arr = np.frombuffer(data, np.uint8)
        frame = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)

        processed_frame = analyze_and_detect(frame)

        _, buffer = cv2.imencode('.jpg', processed_frame)
        img_b64 = base64.b64encode(buffer).decode('utf-8')
        data_url_show = f'data:image/jpeg;base64,{img_b64}'

        eval_js(webcam_show_frame_template.format(data_url=data_url_show))

    except KeyboardInterrupt:
        print("\n⏹️ หยุดการทำงานของกล้องแล้ว")
        display(Javascript('if(window.webcamStream){window.webcamStream.video.srcObject.getTracks().forEach(track => track.stop());}'))
        break
    except Exception as e:
        print(f"\n❌ เกิดข้อผิดพลาด: {e}")
        display(Javascript('if(window.webcamStream){window.webcamStream.video.srcObject.getTracks().forEach(track => track.stop());}'))
        break